"""Pydantic models for iris-client.

- `generated.py` — Phase 6: auto-generated by `datamodel-code-generator`
  from the backend's `/api/openapi.json`. Committed to the repo; CI
  verifies it matches the live schema.
- `exports.py`  — Phase 6: hand-written bundle schemas that mirror
  `backend/app/export/schemas.py` (SPEC-128-A).
"""
